### ISSUE TITLE
Unable to set localhost. This prevents creation of a GUID. Cause was: deluge: deluge: Name or service not known

### ISSUE THREAD

**Issue by edifus** [Laharah/deluge-FileBotTool#48]
Deluge Daemon 1.3.15
Deluge Client 1.3.15
Filebot 4.9.2 (r8046)
OpenJDK 11.0.8
Linux 5.4.0

Getting error when I do a dry run. Execute functions normally.

```
stderr:
    Oct 10, 2020 8:54:16 PM net.sf.ehcache.Cache <clinit>
    SEVERE: Unable to set localhost. This prevents creation of a GUID. Cause was: deluge: deluge: Name or service not known
    java.net.UnknownHostException: deluge: deluge: Name or service not known
    	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1642)
    	at net.sf.ehcache.Cache.<clinit>(Cache.java:222)
    	at net.filebot.DiskStore.lambda$getCache$0(Unknown Source)
    	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    	at net.filebot.DiskStore.getCache(Unknown Source)
    	at net.filebot.Cache.getCache(Unknown Source)
    	at net.filebot.media.ReleaseInfo.lambda$resource$29(Unknown Source)
    	at net.filebot.MemoizedResource.get(Unknown Source)
    	at net.filebot.media.ReleaseInfo.getAnidbIndex(Unknown Source)
    	at net.filebot.Parallelism.lambda$async$1(Unknown Source)
    	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    	at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.net.UnknownHostException: deluge: Name or service not known
    	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
    	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
    	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
    	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
    	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1637)
    	... 13 more
```

**Comment by Laharah** [comment]
This looks like a generic java issue, not necessarily related to deluge/filebot.

Looking around online the two things I would check are:

1. It looks like your server's hostname is `deluge` and java is trying to look it up on your DNS server and not finding anything. Check and make sure that `deluge` is a valid alias for localhost by putting this in your `/etc/hosts` file:
```
127.0.0.1   deluge    localhost
```

2.  If that doesn't work, try using the oracle JDK, there seems to be something about your configuration java doesn't like.

**Comment by edifus** [comment]
Never needed it before and the only change was updating Filebot from 4.9.1 (unknown build, sorry) to Filebot 4.9.2 (r8046). I tried setting the hosts entry but still get the warning window running a dry run, except now stderr is completely blank. If I remove the hosts entry its back to the original behavior. The warning window shows the results of a test run, just think it cant get the output captured to display in the plugin window.

Again, running normally and executing Filebot works. Just the preview from dry-run doesn't display in the plugin and instead get a warning with the error I posted originally.

Is there some additional logging I can enable that might help track this issue down?

---
Full output of the warning - clicking the "more details" button on the warning window doesn't give me anything more.

```
FilebotRuntimeError error on torrent 9cd145943fc37065148126e1baa04dbcd5345eab:
    FILEBOT OUTPUT DUMP:
    Rename movies using [TheMovieDB]
    Auto-detect movie from context [/data/downloads/unsorted/The.Fifth.Element.1997.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.HYBRID.REMUX-FraMeSToR/The.Fifth.Element.1997.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.HYBRID.REMUX-FraMeSToR.mkv]
    [TEST] from [/data/downloads/unsorted/The.Fifth.Element.1997.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.HYBRID.REMUX-FraMeSToR/The.Fifth.Element.1997.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.HYBRID.REMUX-FraMeSToR.mkv] to [/data/downloads/unsorted/The.Fifth.Element.1997.UHD.BluRay.2160p.TrueHD.Atmos.7.1.HEVC.HYBRID.REMUX-FraMeSToR/The.Fifth.Element.1997.BluRay.Remux.2160p.HEVC.HDR10.TrueHD-Atmos7.1-FraMeSToR.mkv]
    Processed 1 file
    
    stderr:
    Oct 12, 2020 10:29:59 AM net.sf.ehcache.Cache <clinit>
    SEVERE: Unable to set localhost. This prevents creation of a GUID. Cause was: deluge: deluge: Name or service not known
    java.net.UnknownHostException: deluge: deluge: Name or service not known
    	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1642)
    	at net.sf.ehcache.Cache.<clinit>(Cache.java:222)
    	at net.filebot.DiskStore.lambda$getCache$0(Unknown Source)
    	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
    	at net.filebot.DiskStore.getCache(Unknown Source)
    	at net.filebot.Cache.getCache(Unknown Source)
    	at net.filebot.media.ReleaseInfo.lambda$resource$29(Unknown Source)
    	at net.filebot.MemoizedResource.get(Unknown Source)
    	at net.filebot.media.ReleaseInfo.getStructureRootPattern(Unknown Source)
    	at net.filebot.media.MediaFileUtilities.matchStructureRootPattern(Unknown Source)
    	at net.filebot.media.MediaFileUtilities.isStructureRoot(Unknown Source)
    	at net.filebot.media.MediaDetection.guessMovieFolder(Unknown Source)
    	at net.filebot.media.MediaDetection.detectMovie(Unknown Source)
    	at net.filebot.media.MediaDetection.detectMovieWithYear(Unknown Source)
    	at net.filebot.cli.CmdlineOperations.renameMovie(Unknown Source)
    	at net.filebot.cli.CmdlineOperations.rename(Unknown Source)
    	at net.filebot.cli.ArgumentProcessor.runCommand(Unknown Source)
    	at net.filebot.cli.ArgumentProcessor.run(Unknown Source)
    	at net.filebot.Main.main(Unknown Source)
    Caused by: java.net.UnknownHostException: deluge: Name or service not known
    	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
    	at java.base/java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
    	at java.base/java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
    	at java.base/java.net.InetAddress.getAllByName0(InetAddress.java:1505)
    	at java.base/java.net.InetAddress.getLocalHost(InetAddress.java:1637)
    	... 18 more
```

**Comment by Laharah** [comment]
Ah, I see. The test actually seems to run okay, the output dump before the stderr is actually fine, that's what a successful rename looks like. I've updated to 4.9.2 and I'm getting the same issue, though without the unknown host exceptions, so it looks like the host file change did work to fix that.

I guess something about the way `[TEST]` runs are reported changed in filebot 4.9.2 and the plugin isn't reading them correctly anymore. I'll take a look and see what it is and hopefully put out a patch later today.

**Comment by Laharah** [comment]
Added a patch for the new FileBot behavior. It's live in [Version 1.2.11](https://github.com/Laharah/deluge-FileBotTool/releases/tag/1.2.11).

It's fixed the errors it in my tests, but feel free to re-open this if you're still running into the same issue. 
Thanks for the report!
